<?php
// $Id$

require_once 'maxlength.inc';

function maxlength_uninstall() {
  foreach (node_get_types() as $type => $name) {
    $code = MAXLENGTH_NODE_TYPE . $type;
    
    // old variables, not used anymore
    variable_del($code . '_limit');
    variable_del($code . '_maxlength');
    
    // current variables
    variable_del($code . '_maxlength_title');
    variable_del($code . '_maxlength_body');
  }
}

?>